/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as EditSetupRouteImport } from './routes/edit-setup'
import { Route as EditRouteImport } from './routes/edit'
import { Route as DevRouteImport } from './routes/dev'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsGenerationIdRouteImport } from './routes/results.$generationId'
import { Route as EditResultEditIdRouteImport } from './routes/edit-result.$editId'
import { Route as ImageGenerationIdIndexRouteImport } from './routes/image.$generationId.$index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const EditSetupRoute = EditSetupRouteImport.update({
  id: '/edit-setup',
  path: '/edit-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsGenerationIdRoute = ResultsGenerationIdRouteImport.update({
  id: '/results/$generationId',
  path: '/results/$generationId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditResultEditIdRoute = EditResultEditIdRouteImport.update({
  id: '/edit-result/$editId',
  path: '/edit-result/$editId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGenerationIdIndexRoute = ImageGenerationIdIndexRouteImport.update({
  id: '/image/$generationId/$index',
  path: '/image/$generationId/$index',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/edit': typeof EditRoute
  '/edit-setup': typeof EditSetupRoute
  '/editing': typeof EditingRoute
  '/flows': typeof FlowsRoute
  '/generate': typeof GenerateRoute
  '/generating': typeof GeneratingRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/edit-result/$editId': typeof EditResultEditIdRoute
  '/results/$generationId': typeof ResultsGenerationIdRoute
  '/image/$generationId/$index': typeof ImageGenerationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/edit': typeof EditRoute
  '/edit-setup': typeof EditSetupRoute
  '/editing': typeof EditingRoute
  '/flows': typeof FlowsRoute
  '/generate': typeof GenerateRoute
  '/generating': typeof GeneratingRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/edit-result/$editId': typeof EditResultEditIdRoute
  '/results/$generationId': typeof ResultsGenerationIdRoute
  '/image/$generationId/$index': typeof ImageGenerationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/edit': typeof EditRoute
  '/edit-setup': typeof EditSetupRoute
  '/editing': typeof EditingRoute
  '/flows': typeof FlowsRoute
  '/generate': typeof GenerateRoute
  '/generating': typeof GeneratingRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/edit-result/$editId': typeof EditResultEditIdRoute
  '/results/$generationId': typeof ResultsGenerationIdRoute
  '/image/$generationId/$index': typeof ImageGenerationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/edit'
    | '/edit-setup'
    | '/editing'
    | '/flows'
    | '/generate'
    | '/generating'
    | '/history'
    | '/settings'
    | '/edit-result/$editId'
    | '/results/$generationId'
    | '/image/$generationId/$index'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/edit'
    | '/edit-setup'
    | '/editing'
    | '/flows'
    | '/generate'
    | '/generating'
    | '/history'
    | '/settings'
    | '/edit-result/$editId'
    | '/results/$generationId'
    | '/image/$generationId/$index'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/edit'
    | '/edit-setup'
    | '/editing'
    | '/flows'
    | '/generate'
    | '/generating'
    | '/history'
    | '/settings'
    | '/edit-result/$editId'
    | '/results/$generationId'
    | '/image/$generationId/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRoute
  EditRoute: typeof EditRoute
  EditSetupRoute: typeof EditSetupRoute
  EditingRoute: typeof EditingRoute
  FlowsRoute: typeof FlowsRoute
  GenerateRoute: typeof GenerateRoute
  GeneratingRoute: typeof GeneratingRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  EditResultEditIdRoute: typeof EditResultEditIdRoute
  ResultsGenerationIdRoute: typeof ResultsGenerationIdRoute
  ImageGenerationIdIndexRoute: typeof ImageGenerationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-setup': {
      id: '/edit-setup'
      path: '/edit-setup'
      fullPath: '/edit-setup'
      preLoaderRoute: typeof EditSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$generationId': {
      id: '/results/$generationId'
      path: '/results/$generationId'
      fullPath: '/results/$generationId'
      preLoaderRoute: typeof ResultsGenerationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-result/$editId': {
      id: '/edit-result/$editId'
      path: '/edit-result/$editId'
      fullPath: '/edit-result/$editId'
      preLoaderRoute: typeof EditResultEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/$generationId/$index': {
      id: '/image/$generationId/$index'
      path: '/image/$generationId/$index'
      fullPath: '/image/$generationId/$index'
      preLoaderRoute: typeof ImageGenerationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRoute,
  EditRoute: EditRoute,
  EditSetupRoute: EditSetupRoute,
  EditingRoute: EditingRoute,
  FlowsRoute: FlowsRoute,
  GenerateRoute: GenerateRoute,
  GeneratingRoute: GeneratingRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  EditResultEditIdRoute: EditResultEditIdRoute,
  ResultsGenerationIdRoute: ResultsGenerationIdRoute,
  ImageGenerationIdIndexRoute: ImageGenerationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
